// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7TwEMZTTDOHsjFSyex8O35GnoglM2ZgE',
    appId: '1:1082069999245:web:6ef3a07a1e4888823bccc4',
    messagingSenderId: '1082069999245',
    projectId: 'etracker-478d3',
    authDomain: 'etracker-478d3.firebaseapp.com',
    storageBucket: 'etracker-478d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXTloRCw97L2QdlfVU-zG9DXmJ3Ak5y2g',
    appId: '1:1082069999245:android:c596dd7b9f689c1f3bccc4',
    messagingSenderId: '1082069999245',
    projectId: 'etracker-478d3',
    storageBucket: 'etracker-478d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOLEPNZgDSxTAblXdwwZBbFgG-RZRPWvs',
    appId: '1:1082069999245:ios:621a1f493af411593bccc4',
    messagingSenderId: '1082069999245',
    projectId: 'etracker-478d3',
    storageBucket: 'etracker-478d3.appspot.com',
    iosBundleId: 'com.example.fourthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOLEPNZgDSxTAblXdwwZBbFgG-RZRPWvs',
    appId: '1:1082069999245:ios:3d876f5e4d3f24953bccc4',
    messagingSenderId: '1082069999245',
    projectId: 'etracker-478d3',
    storageBucket: 'etracker-478d3.appspot.com',
    iosBundleId: 'com.example.fourthApp.RunnerTests',
  );
}
